### ISSUE TITLE
Mixed packages issue

### ISSUE THREAD

**Issue by prestonvanloon** [quic-go/qtls-go1-18#1]
Hi Marten,

Our tooling for bazel is complaining about two package names in the same directory. The impact here is that we are seeing an additional warning message when building.
```
gazelle: found packages qtls (auth.go) and main (generate_cert.go)
```

Although the file is tagged "build:ignore" our tooling still reads all go files to see what needs to be provided to the go toolchain.
Could this generate_cert.go file be moved or removed entirely?

**Comment by marten-seemann** [comment]
This seems to be a problem in your tooling, not in this repo.

The file (`generate_cert.go`) was copied from the standard library: https://github.com/golang/go/blob/master/src/crypto/tls/generate_cert.go.

**Comment by prestonvanloon** [comment]
Sure, I understand the problem can be solved in the tooling. The tooling _should_ read build tags. However, it would be much faster to solve it here (I hope).

The problem could also be solved by deleting it from this repository. 
Is it used at all or serve any value? 
Why copy it from that repo instead of using that repo?

**Comment by marten-seemann** [comment]
> The problem could also be solved by deleting it from this repository.
> Is it used at all or serve any value?
> Why copy it from that repo instead of using that repo?

For the qtls repos, we just copy whatever is in `crypto/tls`, and then do the QUIC-specific modifications. We have to do the same thing for every Go version (and every time `crypto/tls` is updated).
I'm surprised your tooling only chokes on the file in Go 1.18, this file also in the [Go 1.17 version](https://github.com/marten-seemann/qtls-go1-17/blob/master/generate_cert.go).

**Comment by prestonvanloon** [comment]
Ah OK, I understand. This may be a greater issue with the tooling in that case. I'll try to find the root cause and solve it there. Thanks!

**Comment by arashpayan** [comment]
@prestonvanloon, I'm experiencing the same error with bazel. Were you able to figure out why this is happening specifically with 1.18 and not earlier versions?

**Comment by prestonvanloon** [comment]
@arashpayan I set a gazelle exclusion directive like this

```python
    go_repository(
        name = "com_github_marten_seemann_qtls_go1_18",
        build_directives = [
            "gazelle:exclude generate_cert.go",
        ],
        importpath = "github.com/marten-seemann/qtls-go1-18",
        sum = "h1:qp7p7XXUFL7fpBvSS1sWD+uSqPvzNQK43DH+/qEkj0Y=",
        version = "v0.1.1",
    )
```

https://github.com/prysmaticlabs/prysm/pull/10423

Edit: I did not find the root cause. I think this use of build:ignore is inappropriate so I haven't really spent much time on it.

Edit2: The only diff I can see is that go1.17 version uses both style of go build constraints

```
//go:build ignore
// +build ignore
```

**Comment by arashpayan** [comment]
Thanks @prestonvanloon! The exclusion fixed it.

I think it has to do with the new style build constraints not being parsed or propagated. I'll open up an issue with rules_go next week or so.
